
name: Build Android APK
on:
  push:
    paths:
      - 'project.zip' # Trigger ONLY when the IDE uploads this file

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      - name: Install Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Install Cordova
        run: npm install -g cordova

      - name: Create Cordova Project
        run: |
          cordova create app com.mobileide.app MyMobileApp
          cd app
          cordova platform add android

      - name: Inject Source Code
        run: |
          # Unzip the file uploaded by the IDE into the www folder
          rm -rf app/www/*
          unzip project.zip -d app/www/

      - name: Build APK
        run: |
          cd app
          cordova build android --release -- --packageType=apk

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v3
        with:
          name: debug-apk
          path: app/platforms/android/app/build/outputs/apk/release/app-release-unsigned.apk
